{
  "headers": {
    "client_id": "jfhsfhshsdhfe",
    "client_secret": "fhesjfhesjfsehj",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.40.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "5582f743-03e5-4119-8903-7265297193e8",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "324"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employee/253",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employee/253",
  "listenerPath": "/api/*",
  "relativePath": "/api/employee/253",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/employee/253",
  "rawRequestPath": "/api/employee/253",
  "remoteAddress": "/127.0.0.1:52735",
  "requestPath": "/api/employee/253"
}